name: Update README

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal tiene otro nombre

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.2'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Generate TOC
      run: |
        python script.py

    - name: Commit changes
      run: |
        git config --global user.name "PyBot"
        git config --global user.email "pybot@users.noreply.github.com"
        git add README.md
        git commit -m "Automatically update README content section" || echo "No changes to commit"
        git push
